version: '3.5'

services:
  taiga-db:
    image: postgres:12.3
    container_name: taiga-db
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: taigaio/taiga-back:6.0.0
    container_name: taiga-back
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
      POSTGRES_HOST: taiga-db
      TAIGA_SECRET_KEY: "taiga-secret-key"
      TAIGA_SITES_DOMAIN: "${RENDER_EXTERNAL_HOSTNAME}"
      TAIGA_SITES_SCHEME: "https"
    depends_on:
      - taiga-db
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:6.0.0
    container_name: taiga-front
    environment:
      TAIGA_URL: "https://${RENDER_EXTERNAL_HOSTNAME}"
      TAIGA_WEBSOCKETS_URL: "wss://${RENDER_EXTERNAL_HOSTNAME}"
    networks:
      - taiga

  taiga-events:
    image: taigaio/taiga-events:6.0.0
    container_name: taiga-events
    environment:
      TAIGA_SECRET_KEY: "taiga-secret-key"
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:6.0.0
    container_name: taiga-protected
    environment:
      TAIGA_SECRET_KEY: "taiga-secret-key"
    networks:
      - taiga

  taiga-gateway:
    image: taigaio/taiga-gateway:6.0.0
    container_name: taiga-gateway
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events
      - taiga-protected
    networks:
      - taiga

volumes:
  taiga-db-data:

networks:
  taiga:
