services:
  # Taiga Web Service
  - type: web
    name: taiga
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          name: taiga
          type: web
          property: host
      - key: POSTGRES_HOST
        fromService:
          name: taiga-postgres
          type: pserv
          property: host
      - key: POSTGRES_USER
        value: taiga
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        value: taiga
      - key: TAIGA_SECRET_KEY
        generateValue: true
    healthCheckPath: /api/v1/health
    
  # Postgres Database
  - type: pserv
    name: taiga-postgres
    env: docker
    repo: https://github.com/render-examples/postgres.git
    plan: standard
    envVars:
      - key: POSTGRES_USER
        value: taiga
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        value: taiga
