services:
  # Taiga Main Service
  - type: web
    name: taiga
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    envVars:
      - key: TAIGA_SITES_DOMAIN
        fromService:
          name: taiga
          type: web
          property: host
      - key: TAIGA_SITES_SCHEME
        value: https
      - key: TAIGA_SECRET_KEY
        generateValue: true
      - key: POSTGRES_HOST
        fromService:
          name: taiga-postgres
          type: pserv
          property: host
      - key: POSTGRES_USER
        value: taiga
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        value: taiga
    
  # Postgres Database
  - type: pserv
    name: taiga-postgres
    env: docker
    repo: https://github.com/render-examples/postgres.git
    plan: standard
    envVars:
      - key: POSTGRES_USER
        value: taiga
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        value: taiga
